// <auto-generated />
using Coach2Go.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Coach2Go.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250617165307_AddUserWorkoutFields")]
    partial class AddUserWorkoutFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Coach2Go.Api.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "40 secs",
                            ImagePath = "images/jumping-jack.png",
                            Name = "Jumping Jacks",
                            WorkoutSessionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Details = "12 reps",
                            ImagePath = "images/squat.png",
                            Name = "Squats",
                            WorkoutSessionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Details = "10 reps",
                            ImagePath = "images/pushup.png",
                            Name = "Push Ups",
                            WorkoutSessionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Details = "15 reps",
                            ImagePath = "images/glutebridges.png",
                            Name = "Glute Bridges",
                            WorkoutSessionId = 1
                        },
                        new
                        {
                            Id = 5,
                            Details = "1 min",
                            ImagePath = "images/plank.png",
                            Name = "Plank",
                            WorkoutSessionId = 1
                        });
                });

            modelBuilder.Entity("Coach2Go.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WorkoutPlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutPlanId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ana@test.com",
                            Experience = "Beginner",
                            Goal = "Lose Weight",
                            Type = "Bodyweight",
                            Username = "Ana",
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "elijah@test.com",
                            Experience = "Intermediate",
                            Goal = "Strength",
                            Type = "Gym",
                            Username = "Elijah",
                            WorkoutPlanId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@test.com",
                            Experience = "Beginner",
                            Goal = "General Fitness",
                            Type = "Bodyweight",
                            Username = "Charlie",
                            WorkoutPlanId = 3
                        },
                        new
                        {
                            Id = 4,
                            Email = "sasha@test.com",
                            Experience = "Advanced",
                            Goal = "Build Muscle",
                            Type = "Gym",
                            Username = "Sasha",
                            WorkoutPlanId = 4
                        },
                        new
                        {
                            Id = 5,
                            Email = "sham@test.com",
                            Experience = "Beginner",
                            Goal = "Build Muscle",
                            Type = "Gym",
                            Username = "Sham",
                            WorkoutPlanId = 5
                        },
                        new
                        {
                            Id = 6,
                            Email = "blessing@test.com",
                            Experience = "Beginner",
                            Goal = "Lose weight",
                            Type = "Gym",
                            Username = "Blessing",
                            WorkoutPlanId = 6
                        });
                });

            modelBuilder.Entity("Coach2Go.Api.Models.WorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 20,
                            Experience = "Beginner",
                            Goal = "Lose Weight",
                            Intensity = "Low",
                            Type = "Bodyweight"
                        },
                        new
                        {
                            Id = 2,
                            Duration = 40,
                            Experience = "Intermediate",
                            Goal = "Strength",
                            Intensity = "Medium",
                            Type = "Gym"
                        },
                        new
                        {
                            Id = 3,
                            Duration = 30,
                            Experience = "Beginner",
                            Goal = "General Fitness",
                            Intensity = "Low",
                            Type = "Bodyweight"
                        },
                        new
                        {
                            Id = 4,
                            Duration = 50,
                            Experience = "Advanced",
                            Goal = "Build Muscle",
                            Intensity = "High",
                            Type = "Gym"
                        },
                        new
                        {
                            Id = 5,
                            Duration = 35,
                            Experience = "Beginner",
                            Goal = "Build Muscle",
                            Intensity = "Medium",
                            Type = "Gym"
                        },
                        new
                        {
                            Id = 6,
                            Duration = 30,
                            Experience = "Beginner",
                            Goal = "Lose Weight",
                            Intensity = "Low",
                            Type = "Gym"
                        });
                });

            modelBuilder.Entity("Coach2Go.Api.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("WorkoutSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Recommended",
                            Day = "Monday",
                            Duration = 30,
                            ImagePath = "images/workout1.jpg",
                            Title = "Full Body",
                            Week = 1,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Popular",
                            Day = "Tuesday",
                            Duration = 30,
                            ImagePath = "images/cardiocore.jpg",
                            Title = "Cardio & Core",
                            Week = 1,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Recovery",
                            Day = "Wednesday",
                            Duration = 20,
                            ImagePath = "images/activerecovery1.jpg",
                            Title = "Active Recovery",
                            Week = 1,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "",
                            Day = "Thursday",
                            Duration = 25,
                            ImagePath = "images/lowerbody.jpg",
                            Title = "Lower Body",
                            Week = 1,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "",
                            Day = "Friday",
                            Duration = 30,
                            ImagePath = "images/hiit.jpg",
                            Title = "HIIT",
                            Week = 1,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = "",
                            Day = "Saturday",
                            Duration = 20,
                            ImagePath = "images/yoga.jpg",
                            Title = "Yoga",
                            Week = 1,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 7,
                            Category = "",
                            Day = "Monday",
                            Duration = 25,
                            ImagePath = "images/fullbodyblast.jpg",
                            Title = "Full-Body Blast",
                            Week = 2,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 8,
                            Category = "",
                            Day = "Tuesday",
                            Duration = 25,
                            ImagePath = "images/coreburn.jpg",
                            Title = "Core Focus Burn",
                            Week = 2,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 9,
                            Category = "",
                            Day = "Monday",
                            Duration = 30,
                            ImagePath = "images/powercore.jpg",
                            Title = "Power Core",
                            Week = 3,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 10,
                            Category = "",
                            Day = "Tuesday",
                            Duration = 20,
                            ImagePath = "images/mobility.jpg",
                            Title = "Light Flow & Mobility",
                            Week = 3,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 11,
                            Category = "",
                            Day = "Monday",
                            Duration = 40,
                            ImagePath = "images/strength.jpg",
                            Title = "Strength Circuit",
                            Week = 4,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 12,
                            Category = "",
                            Day = "Tuesday",
                            Duration = 30,
                            ImagePath = "images/agility.jpg",
                            Title = "Agility",
                            Week = 4,
                            WorkoutPlanId = 1
                        });
                });

            modelBuilder.Entity("Coach2Go.Api.Models.Exercise", b =>
                {
                    b.HasOne("Coach2Go.Api.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Coach2Go.Api.Models.User", b =>
                {
                    b.HasOne("Coach2Go.Api.Models.WorkoutPlan", "WorkoutPlan")
                        .WithOne("User")
                        .HasForeignKey("Coach2Go.Api.Models.User", "WorkoutPlanId");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("Coach2Go.Api.Models.WorkoutSession", b =>
                {
                    b.HasOne("Coach2Go.Api.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("Coach2Go.Api.Models.WorkoutPlan", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Coach2Go.Api.Models.WorkoutSession", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
